config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'pages#main'

  get 'rent-a-yoda' => 'pages#rent'
  get 'cart' => 'pages#cart'
  get 'warranty' => 'pages#warranty'
  get 'faq' => 'pages#faq'
  get 'delivery' => 'pages#delivery'
  get 'returns' => 'pages#returns'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-of-use' => 'pages#terms_of_use'


  resources :contact, only: [:create]
  get 'contact' => 'contact#contact'


  get 'users/create' => 'users#create'
  post 'users/subscribe' => 'users#create_subscriber'
  post 'users/email-verification' => 'users#email_verification'
  get 'rent-a-yoda/refer-a-friend' => 'users#refer'
end

app/models/user.rb
require 'users_helper'

class User < ApplicationRecord
  belongs_to :referrer, class_name: 'User', foreign_key: 'referrer_id', required: false
  has_many :referrals, class_name: 'User', foreign_key: 'referrer_id'

  validates :email, presence: true, uniqueness: true, format: {
    with: /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/i,
    message: 'Invalid email format.'
  }

  before_create :create_referral_code
  before_create :downcase_email

  REFERRAL_STEPS = [
    {
      'count' => 25,
      'html' => '1 Free T-shirt',
      'class' => 'one',
      # 'image' => ActionController::Base.helpers.image_path("reduc_3.png")
    },
    {
      'count' => 100,
      'html' => '1 Free Rain-jacket',
      'class' => 'two',
      # 'image' => ActionController::Base.helpers.asset_path(
      #   'refer/blade-explain@2x.png')
    }
  ]
  REFERRAL_STEPS_MOBILE = [
    {
      'count' => 25,
      'html' => '1 Free<br>T-shirt',
      'class' => 'one',
      # 'image' => ActionController::Base.helpers.image_path("reduc_3.png")
    },
    {
      'count' => 100,
      'html' => '1 Free<br>Rain-jacket',
      'class' => 'two',
      # 'image' => ActionController::Base.helpers.asset_path(
      #   'refer/blade-explain@2x.png')
    }
  ]

  private

  def downcase_email
    self.email.downcase!
  end

  def create_referral_code
    self.referral_code = UsersHelper.unused_referral_code
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_variant, only: [:refer]


  def create
    @referrer_code = params[:param2] # "value2"
    @user = User.new(email: params[:param1])
    @user.referrer = User.find_by_referral_code(@referrer_code) if @referrer_code
    if @user.save
      cookies[:h_email] = { value: @user.email, expires: 52.week.from_now }
      redirect_to rent_a_yoda_refer_a_friend_path
    else
      logger.info('Error saving user')
      redirect_to rent_a_yoda_path, alert: 'Error saving your email'
    end
  end

  def create_subscriber
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, alert: "Thank you for your subscribtion."
    else
      # render :new => ca c'est si on veut rediriger vers une def local
      redirect_to root_path, alert: "something went wrong"
    end
  end

  def refer
    @refer_friend_navbar = true

    session[:expires_at] = Time.now + 5
    @nav_link_refer = true
    @user = User.find_by_email(cookies[:h_email])

    if @user.nil?
      respond_to do |format|
        format.html(&:phone)
        redirect_to root_path, alert: 'Something went wrong!'
      end
    else
      respond_to do |format|
        format.html(&:phone) # refer.html.erb
      end
    end
  end

  def email_verification
    ref_code = cookies[:h_ref]
    @user = User.new(user_params)
    @user.referrer = User.find_by_referral_code(ref_code) if ref_code

    if User.find_by_email(@user.email).nil?
      if @user.valid?
        UserMailer.email_verification(@user).deliver_now
      else
        redirect_to rent_a_yoda_path, alert: 'Error sending your email. Try again.'
      end
    else
      logger.info('This user already subscribed')
      redirect_to rent_a_yoda_path, alert: 'This user already subscribed'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end

  def set_variant
    case request.user_agent
    when /iPhone/i
      request.variant = :phone
    when /Android/i && /mobile/i
      request.variant = :phone
    when /Windows Phone/i
      request.variant = :phone
    # when /Android/i
    #   request.variant = :tablet
    # when /iPad/i
    #   request.variant = :tablet
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def self.unused_referral_code
    referral_code = SecureRandom.hex(5)
    collision = User.find_by_referral_code(referral_code)

    until collision.nil?
      referral_code = SecureRandom.hex(5)
      collision = User.find_by_referral_code(referral_code)
    end
    referral_code
  end
end

app/views/users/refer.html+phone.erb
<%= render "shared/navbar-mobile" %>

<div class="refer-mobile-container">
  <div id="refer-bottom" class="first-refer-friends-mobile-container">
    <div class="refer-main-mobile-text-1">
      <h2>D'ont leave your friends behind!</h2>
      <h1><span>INVITE</span> FRIENDS &<br>EARN KILOMETERS</h1>
      <div class="copy-link"><%= root_url %>?ref=<%= @user.referral_code %></div>
      <% twitter_message = "#Mobility is evolving. Excited for YodaCity to launch." %>
      <div class="social-links">
        <a href="http://www.facebook.com/sharer/sharer.php?u=<%= CGI::escape(root_url) %>?ref=<%= CGI::escape(@user.referral_code) %>&title=YodaCity" target="_blank"><i class="fab fa-facebook" style="color: #001C7A;"></i></a>
        <div class="sep"></div>
        <a href="http://twitter.com/share?url=<%= CGI::escape(root_url) %>?ref=<%= CGI::escape(@user.referral_code) %>&text=<%= CGI::escape(twitter_message) %>" class="twit" target="_blank"><i class="fab fa-twitter-square" style="color: #001C7A;"></i></a>
        <a href="https://www.linkedin.com/shareArticle?mini=true&url=<%= CGI::escape(rent_a_yoda_url) %>?ref=<%= CGI::escape(@user.referral_code) %>&title=Own your city back&summary=Mobility is evolving. Didn’t want to leave you all behind. Check out YodaCity here&source=yoda-city.com" class="linkedin" target="_blank"><i class="fab fa-linkedin"></i></a>
      </div>
      <p style="margin-top: 0px; margin-bottom: 20px; color: #001C7A;">Your unique link works with those three buttons too :-)</p>
      <p>You can also share your unique link via Email Messenger or Instagram to earn YodaCity rewards.</p>
    </div>
    <%= image_tag('Yoda/Mobile/Yoda-refer-friend-mobile@2x.png', class: "yoda-image") %>
  </div>



<%

  if @user.referrals.count <= 100
    referrals_count = @user.referrals.count
  else
    referrals_count = 100
  end

  stops = User::REFERRAL_STEPS_MOBILE

  found = nil

  stops.reverse_each { |stop|
    if stop["count"] <= referrals_count and !found
      stop["selected"] = true
      found = stop
    else
      stop["selected"] = false
    end
  }
%>
<%
  word_friend = ''
  word_meter = ''
  if referrals_count == 0
    word_friend = 'Friend'
    word_meter = 'Meter'
    meter = 0
  elsif referrals_count == 1
    word_friend = 'Friend'
    word_meter = 'Meters'
    meter = 500
  else
    word_friend = 'Friends'
    word_meter = 'Meters'
    meter = nil
  end
%>
<%
width_bar = 0
if referrals_count <= 25
  width_bar = referrals_count*5.52
else
  width_bar = referrals_count*3.65
end
%>



  <div class="prizes-friends-mobile-container <% if found %>prize-mobile-<%=found["class"]%><% end %>">
    <div class="page-content-top">
      <p class="callout">1 friend = 500 Meters</p>
    </div>

    <ul class="products">
      <li class="title">
        <p class="friends"><%= referrals_count %> <%= word_friend %></p>
        <p class="rewards">
        <%=
        if !meter.nil?
          meter
        else
          (referrals_count/2.0*1000).to_i
        end
        %> <%= word_meter %></p>
      </li>
      <% stops.each do |stop| %>
        <li class="product <% if stop["selected"] %>selected<% end %>">
          <div class="circle"><%= stop["count"] %></div>
          <div class="sep"></div>
          <p><%= stop["html"].html_safe %></p>

          <div class="tooltip">
            <img src="<%= stop["image"] %>" height="254">
          </div>
        </li>
      <% end %>
      <div class="progress">
        <div class="mover">
          <div id="bar"></div>
          <div class="yoda-icon"><%= image_tag('Refer/Yoda-icon.png') %></div>
        </div>
      </div>
      <i class="fas fa-flag-checkered"></i>
    </ul>
     <%
        words = ''
        if referrals_count == 1
          words = 'friend has'
        else
          words = 'friends have'
        end
      %>

      <% if referrals_count == 0 %>
        <p class="place"><span>No</span> friends have joined...Yet!</p>
        <p class="place check">Keep checking...</p>
      <% elsif referrals_count <= 99 %>
        <p class="place"><span id="friend"><%= referrals_count %></span> <%= words %> joined</p>
      <%else %>
        <p class="place"><span id="friend"><%= referrals_count %></span> <%= words %> joined</p>
        <p class="place check">Congratulation!</p>
      <% end %>
  </div>
</div>







<div class="rent-mobile-container">
  <div class="page-mobile-container">
    <div id ="page-mobile-rent-1" class="page-mobile-content-1">
      <div class="text-container">
        <div class="text-content">
          <h1>1€ = 1km<span>.</span></h1>
          <p>Pay for kilometers, not for red lights.🚦</p>
          <%= link_to "#km-order" do %>Get free km<% end %>
        </div>
      </div>
      <div class="image">
        <%= image_tag('Yoda/Mobile/Yoda-left-profile-rent-2@2x.png') %>
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <div class="page-mobile-content-2">
      <div class="text-container">
        <div class="text-content">
          <h2>No pedals<span>.</span></h2>
          <p>Move efficiently and have fun, what more? </p>
          <%= link_to "#km-order" do %>Get free km<% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <div class="page-mobile-content-3">
      <div class="text-container">
        <div class="text-content">
          <h2>Take a ride<span>.</span></h2>
          <p>Max. speed: 45 km/h. You need a car license (B)<br>or a motorcycle license (A3 or AM)</p>
          <%= link_to "#km-order" do %>Get free km<% end %>
        </div>
      </div>
      <div class="image">
        <%= image_tag('App/Mobile/iphone_X_free-floating-mobile-map@2x.png', class: 'iphone_X') %>
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <div class="page-mobile-content-4">
      <div class="text-container">
        <div class="text-content">
          <h2>Experience is key<span>.</span></h2>
          <p>Choose how you want to familiarize yourself with the Yoda. Take it easy.</p>
          <!-- Calendly link widget begin -->
          <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
          <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript"></script>
          <a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/yodacity-test-ride/30min'});return false;">Book a test ride</a>
          <!-- Calendly link widget end -->
        </div>
      </div>
      <div class="image">
        <%= image_tag('App/Mobile/Iphone_X-mobile-Learn-progressively@2x.png') %>
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <div class="page-mobile-content-5">
      <div class="text-container">
        <div class="text-content">
          <h2>A comfy ride<span>.</span></h2>
          <p>Use your phone to navigate while charging it.<br>Sit comfortably.</p>
        </div>
      </div>
      <div class="image">
        <%= image_tag('Yoda/Mobile/Yoda-ff-mobile-comfy-ride@2x.png') %>
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <div id="map" class="map-mobile">
      <%= image_tag('Map-ff-bxl-mobile@2x.png') %>
    </div>
  </div>

  <div class="page-mobile-container">
    <div id="km-order" class="page-mobile-content-6">
      <div class="text-container">
        <div class="text-content">
          <h2>Free kilometers<span>.</span></h2>
          <p class="upercase">GET EARLY KILOMETERS AT 50%</p>
          <div class="price">
            <h4>50KM =</h4>
            <h5>50€</h5>
            <h4 class="red">25€</h4>
          </div>
          <%= link_to "https://yodacity.myshopify.com/cart/31543099195491:1?channel=buy_button" do %>Order 50km<% end %>
        </div>
      </div>
      <div class="image">
        <%= image_tag('Yoda/Mobile/Front-back-view-mobile-order-km@2x.png') %>
      </div>
    </div>
  </div>

  <%= render "shared/footer-mobile" %>
  <div class="footer-mobile-height"></div>
</div>


<script>
  $(document).ready(function() {
      $(window).scroll(function() {
          var height = $('.page-mobile-content-1').height();
          var scrollTop = $(window).scrollTop();

          if (scrollTop >= height - height*0.96) {
              $('.nav-mobile-container').addClass('solid-mobile-nav');
          } else {
              $('.nav-mobile-container').removeClass('solid-mobile-nav');
          }
      });
  });
</script>

<script>
  window.onload=function(){
    var elem = document.getElementById('bar');
    elem.style.height = <%= width_bar %> + 'px';
  }

  var page_1_bottom = $('#page-mobile-rent-1').offset().top + $('#page-mobile-rent-1').height();
  var refer_bottom = $('#refer-bottom').offset().top + $('#refer-bottom').height();
  var map_bottom = $('#map').offset().top + $('#map').height();
  var km_order_bottom = $('#km-order').offset().top + $('#km-order').height();

  $('.nav-mobile-logo-white').css('display', 'none');
  $('.nav-mobile-logo-black').css('display', 'inline');
  // on scroll,
  $(window).on('scroll',function(){

      // we round here to reduce a little workload
      var stop = Math.round($(window).scrollTop());

      if (stop > refer_bottom*0.9 && stop < page_1_bottom) {
          $('.nav-mobile-logo-white').css('display', 'inline');
          $('.nav-mobile-logo-black').css('display', 'none');
          $('.solid-mobile-nav').css('background-color', 'transparent');
      } else if (stop > map_bottom - 30 && stop < km_order_bottom - 200) {
          $('.nav-mobile-logo-white').css('display', 'inline');
          $('.nav-mobile-logo-black').css('display', 'none');
          $('.solid-mobile-nav').css('background-color', 'transparent');
      } else if (stop > km_order_bottom - 200 ) {
          $('.nav-mobile-logo-white').css('display', 'none');
          $('.nav-mobile-logo-black').css('display', 'none');
      }else {
          $('.nav-mobile-logo-white').css('display', 'none');
          $('.nav-mobile-logo-black').css('display', 'inline');
          $('.solid-mobile-nav').css('background-color', 'transparent');
      }

  });
</script>

app/views/users/refer.html.erb
<%= render "shared/navbar" %>
<!-- <div class="navbar-height"></div> -->
<div id="refer-friend-page" class="refer-friends-container">
  <div class="refer-friends-content">


    <div class="refer-friends-top">
        <div class="refer-friends-left"></div>
        <div class="refer-friends-right">
          <div class="text-part">
            <h2>Don't leave your friends behind!</h2>
            <h1><span>INVITE</span> FRIENDS &<br>EARN KILOMETERS</h1>
            <div class="copy-link"><%= root_url %>?ref=<%= @user.referral_code %></div>
            <% twitter_message = "#Mobility is evolving. Excited for YodaCity to launch." %>
            <div class="social-links">

              <a href="http://www.facebook.com/sharer/sharer.php?u=<%= CGI::escape(rent_a_yoda_url) %>?ref=<%= CGI::escape(@user.referral_code) %>&title=YodaCity" class="fb" target="_blank"><i class="fab fa-facebook"></i></a>
              <div class="sep"></div>
              <a href="http://twitter.com/share?url=<%= CGI::escape(rent_a_yoda_url) %>?ref=<%= CGI::escape(@user.referral_code) %>&text=<%= CGI::escape(twitter_message) %>" class="twit" target="_blank"><i class="fab fa-twitter-square"></i></a>
              <div class="sep"></div>
              <a href="https://www.linkedin.com/shareArticle?mini=true&url=<%= CGI::escape(rent_a_yoda_url) %>?ref=<%= CGI::escape(@user.referral_code) %>&title=Own your city back&summary=Mobility is evolving. Didn’t want to leave you all behind. Check out YodaCity here&source=yoda-city.com" class="linkedin" target="_blank"><i class="fab fa-linkedin"></i></a>
            </div>
            <p style="margin-top: 0px; color: #001C7A;">Your unique link works with those three buttons too :-)</p>
            <p>You can also share your unique link via Email, Messenger<br>or Instagram to earn YodaCity rewards.</p>
          </div>
        </div>
    </div>


<%

  if @user.referrals.count <= 100
    referrals_count = @user.referrals.count
  else
    referrals_count = 100
  end

  stops = User::REFERRAL_STEPS

  found = nil

  stops.reverse_each { |stop|
    if stop["count"] <= referrals_count and !found
      stop["selected"] = true
      found = stop
    else
      stop["selected"] = false
    end
  }
%>
<%
  word_friend = ''
  word_meter = ''
  if referrals_count == 0
    word_friend = 'Friend'
    word_meter = 'Meter'
    meter = 0
  elsif referrals_count == 1
    word_friend = 'Friend'
    word_meter = 'Meters'
    meter = 500
  else
    word_friend = 'Friends'
    word_meter = 'Meters'
    meter = nil
  end
%>
<%
width_bar = 0
if referrals_count <= 25
  width_bar = referrals_count*21.8
else
  width_bar = referrals_count*11
end
%>

    <div class="refer-friends-bottom-prizes <% if found %>prize-<%= found["class"] %><% end %>">
      <div class="page-content">
        <p class="callout">1 friend = 500 Meters</p>
        <ul class="products">

          <li class="title">
            <p class="friends"> <%= referrals_count %> <%= word_friend %></p>
            <p class="rewards">
              <%=
                if !meter.nil?
                  meter
                else
                  (referrals_count/2.0*1000).to_i
                end
                %> <%= word_meter %></p>
            </li>

          <% stops.each do |stop| %>

            <li class="product <% if stop["selected"] %>selected<% end %> <% if stop["class"] == 'two' %>last<% end %>">
              <div class="circle"><%= stop["count"] %></div>
              <div class="sep"></div>
              <p><%= stop["html"].html_safe %></p>

              <!-- <div class="tooltip">
                <img src="<%= stop["image"] %>" height="254">
              </div> -->
            </li>

          <% end %>

        </ul>

        <div class="progress">
          <div class="mover">
            <div id="bar"></div>
            <div class="yoda-icon"><%= image_tag('Refer/Yoda-icon.png') %></div>
          </div>
        </div>

        <%
          words = ''
          if referrals_count == 1
            words = 'friend has'
          else
            words = 'friends have'
          end
        %>


        <% if referrals_count == 0 %>
        <p class="place"><span>No</span> friends have joined...Yet!</p>
        <p class="place check">Keep checking...</p>
      <% elsif referrals_count <= 99 %>
        <p class="place"><span id="friend"><%= referrals_count %></span> <%= words %> joined</p>
      <%else %>
        <p class="place"><span id="friend"><%= referrals_count %></span> <%= words %> joined</p>
        <p class="place check">Congratulation!</p>
      <% end %>
        <i class="fas fa-flag-checkered"></i>
      </div>
    </div>
  </div>
</div>

<div class="ff-wrapper-container">

  <div class="rent-page-container">
    <div id ="page-rent-1" class="page-content-1">
      <div class="text-container">
        <h2>1€ = 1km<span>.</span></h2>
        <p>Pay for kilometers, not for red lights.🚦</p>
        <%= link_to "#km-order" do %>50% on km<% end %>
      </div>
    </div>
  </div>

  <div class="rent-page-container">
    <div class="page-content-2">
      <div class="text-container">
        <h2>No pedals<span>.</span></h2>
        <p>Move efficiently and have fun, what more?</p>
        <%= link_to "#km-order" do %>50% on km<% end %>
      </div>
    </div>
  </div>

  <div class="rent-page-container">
    <div class="page-content-3">
      <div class="left-side">
        <%= image_tag('App/iphone_X_free-floating-map@2x.png') %>
      </div>
      <div class="right-side">
        <div class="text-container">
          <h2>Take a ride<span>.</span></h2>
          <!-- <p>Find a Yoda nearby. Ride anywhere with ease.</p> -->
          <p>Max. speed: 45 km/h. You need a car license (B)<br>or a motorcycle license (A3 or AM)</p>
          <%= link_to "#km-order" do %>50% on km<% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="rent-page-container">
    <div class="page-content-4">
      <div class="left-side">
        <div class="text-container">
          <h2>Experience is key<span>.</span></h2>
          <p>Choose how you want to familiarize yourself with the Yoda. Take it easy.</p>
          <!-- Calendly link widget begin -->
          <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
          <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript"></script>
          <a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/yodacity-test-ride/30min'});return false;">Book a test ride</a>
          <!-- Calendly link widget end -->
        </div>
      </div>
      <div class="right-side">
        <%= image_tag('App/Iphone_X-Learn-progressively@2x.png') %>
      </div>
    </div>
  </div>

  <div class="rent-page-container">
    <div class="page-content-5">
      <div class="text-container">
        <h2>A comfy ride<span>.</span></h2>
        <p>Use your phone to navigate while charging it. Sit comfortably.</p>
      </div>
    </div>
  </div>

  <div class="rent-page-container">
    <div id="map" class="map">
      <%= image_tag('Map-ff-bxl@2x.png') %>
    </div>
  </div>

  <div class="rent-page-container">
    <div id="km-order" class="page-content-6">
      <div class="text-container">
        <h2>Free kilometers<span>.</span></h2>
        <p class="upercase">GET EARLY KILOMETERS AT 50%</p>
        <div class="price">
          <h4>50KM =</h4>
          <h5>50€</h5>
          <h4 class="red">25€</h4>
        </div>
        <%= link_to "https://yodacity.myshopify.com/cart/31543099195491:1?channel=buy_button" do %>Order 50km<% end %>
      </div>
    </div>
  </div>

  <%= render "shared/footer" %>
</div>


<script>
  window.onload=function(){
    var elem = document.getElementById('bar');
    elem.style.width = <%= width_bar %> + 'px';
  }

  var page_1_bottom = $('#page-rent-1').offset().top + $('#page-rent-1').height();
  var page_map_bottom = $('#map').offset().top + $('#map').height();
  var refer_friend_page = $('#refer-friend-page').offset().top + $('#refer-friend-page').height();
  $('.nav-logo-white').css('display', 'none');
  $('.nav-logo-black').css('display', 'inline');

  $('.rent').css('border-color', 'black');
  $('.rent').css('background-color', 'white');
  $('.rent').css('color', 'black');
  $('.buy').css('border-color', 'black');
  $('.buy').css('background-color', 'black');
  $('.buy').css('color', 'white');
  // on scroll,
  $(window).on('scroll',function(){

      // we round here to reduce a little workload
      var stop = Math.round($(window).scrollTop());

      if (stop > page_1_bottom && stop < page_map_bottom)  {
          $('.nav-logo-white').css('display', 'none');
          $('.nav-logo-black').css('display', 'inline');

          $('.rent').css('border-color', 'black');
          $('.rent').css('background-color', 'white');
          $('.rent').css('color', 'black');
          $('.buy').css('border-color', 'black');
          $('.buy').css('background-color', 'black');
          $('.buy').css('color', 'white');
      } else {
          $('.nav-logo-white').css('display', 'inline');
          $('.nav-logo-black').css('display', 'none');

          $('.rent').css('border-color', 'white');
          $('.rent').css('background-color', 'black');
          $('.rent').css('color', 'white');
          $('.buy').css('border-color', 'white');
          $('.buy').css('background-color', 'white');
          $('.buy').css('color', 'black');
      }

      if (stop >= page_map_bottom - page_map_bottom*0.01) {
        $('.nav-logo-white').css('display', 'inline');
        $('.nav-logo-black').css('display', 'none');

        $('.rent').css('border-color', 'white');
        $('.rent').css('background-color', 'black');
        $('.rent').css('color', 'white');
        $('.buy').css('border-color', 'white');
        $('.buy').css('background-color', 'white');
        $('.buy').css('color', 'black');
      }

      if (stop < refer_friend_page*0.63) {
        $('.nav-logo-white').css('display', 'none');
        $('.nav-logo-black').css('display', 'inline');

        $('.rent').css('border-color', 'black');
        $('.rent').css('background-color', 'white');
        $('.rent').css('color', 'black');
        $('.buy').css('border-color', 'black');
        $('.buy').css('background-color', 'black');
        $('.buy').css('color', 'white');
      }

  });
</script>