config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'pages#main'

  get 'rent-a-yoda' => 'pages#rent'
  get 'cart' => 'pages#cart'
  get 'warranty' => 'pages#warranty'
  get 'faq' => 'pages#faq'
  get 'delivery' => 'pages#delivery'
  get 'returns' => 'pages#returns'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-of-use' => 'pages#terms_of_use'


  resources :contact, only: [:create]
  get 'contact' => 'contact#contact'


  get 'users/create' => 'users#create'
  post 'users/subscribe' => 'users#create_subscriber'
  post 'users/email-verification' => 'users#email_verification'
  get 'rent-a-yoda/refer-a-friend' => 'users#refer'
end

app/views/shared/_campaign_ended.html.erb
<%= link_to "#km-order" do %>50% on km<% end %>

app/views/shared/_campaign_ongoing.html.erb
<style>
 @import url(https://fonts.googleapis.com/css?family=Lato:400,700);


.login_bar {
  width: 370px;
  height: 50px;
  background: #F7F7F7;
  border-radius: 10px;
  top: 50%;
  position: relative;
  z-index: 1;
  overflow: hidden;
}

.login {
  background: transparent;
  position: absolute;
  height: 100%;
  width: 260px;
  padding-left: 10px;
  text-align: left;
  font-size: 14px;
  border: none;
  line-height: 50px;
  vertical-align: middle;
  z-index: 10;
  -webkit-transition: transform 0.2s ease-in-out 0s;
     -moz-transition: transform 0.2s ease-in-out 0s;
       -o-transition: transform 0.2s ease-in-out 0s;
          transition: transform 0.2s ease-in-out 0s;
}

.login_active {
  -webkit-transform: translateX(370px);
     -moz-transform: translateX(370px);
      -ms-transform: translateX(370px);
       -o-transform: translateX(370px);
          transform: translateX(370px);
}

.subscribe_button:hover{
  background-color: #0091EA;
  /*#282828;*/
  cursor:pointer;
}

.subscribe_button {
  background: #1CA9FF;
  /*#383838;*/

  position: absolute;
  top: -50px;
  left: 271px;
  border-top-right-radius: 10px;
  border-bottom-right-radius: 10px;
  height: 150px;
  width: 100px;
  text-align: center;
  font-size: 14px;
  font-weight: 500;
  line-height: 140px;
  vertical-align: middle;
  color: white;
  -webkit-transition: transform 0.5s ease 0s;
     -moz-transition: transform 0.5s ease 0s;
       -o-transition: transform 0.5s ease 0s;
          transition: transform 0.5s ease 0s;
}

.subscribe_button_active{
  -webkit-transform: translateY(50px);
     -moz-transform: translateY(50px);
      -ms-transform: translateY(50px);
       -o-transform: translateY(50px);
          transform: translateY(50px);
}

.subscribing{
  background: #CDD4DC;
  height: 100%;
  width: 370px;
  z-index: 5;
  position: absolute;
  left:-370px;
  display: inline-block;
  -webkit-transition: transform 1s ease 0s ;
     -moz-transition: transform 1s ease 0s ;
       -o-transition: transform 1s ease 0s ;
          transition: transform 1s ease 0s ;
}

.subscribing_active {
  -webkit-transform: translateX(370px);
     -moz-transform: translateX(370px);
      -ms-transform: translateX(370px);
       -o-transform: translateX(370px);
          transform: translateX(370px);
}

.thanks{
  background: #FFCE00;
  height: 100%;
  width: 370px;
  z-index: 5;
  text-align: left;
  line-height: 50px;
  vertical-align: middle;
  padding-left: 10px;
  position: absolute;
  top:50px;
  display: inline-block;
  -webkit-transition: transform 0.5s ease 0s ;
     -moz-transition: transform 0.5s ease 0s ;
       -o-transition: transform 0.5s ease 0s ;
          transition: transform 0.5s ease 0s ;
}

.thanks_active {
  -webkit-transform: translateY(-50px);
     -moz-transform: translateY(-50px);
      -ms-transform: translateY(-50px);
       -o-transform: translateY(-50px);
          transform: translateY(-50px);
}

</style>

<p class="sub">Be the first to know <span>&</span> get Kilometers</p>
<div class="login_bar">
  <%= form_for @user, url: users_email_verification_path, method: :post do |f| %>
    <%= f.text_field :email, class: "login", :placeholder => "Type in your email" %>
    <input class="submit subscribe_button" onclick="subscribeOnClick()" name="commit" type="submit" value="Step Inside" />
  <% end %>
  <span class="subscribing"></span>
  <span class="thanks">Thank you. Verify your email to get early access.</span>
                                                                        <p></p>
</div>

<script>
var subscribe_button = document.querySelector(".subscribe_button");

subscribe_button.addEventListener('click', function(){
  var subscribing = document.querySelector(".subscribing");
  var thanks = document.querySelector(".thanks");
  var login = document.querySelector(".login");

  subscribing.classList.add("subscribing_active");
  subscribe_button.classList.add("subscribe_button_active");
  setTimeout(function(){
    login.classList.add("login_active");
  }, 1200);
  setTimeout(function(){
    thanks.classList.add("thanks_active");
  }, 1400);

  setTimeout(function(){
    thanks.classList.remove("thanks_active");
    login.classList.remove("login_active");
    subscribing.classList.remove("subscribing_active");
    subscribe_button.classList.remove("subscribe_button_active");
  }, 4000000);
});
</script>

app/views/shared/_campaign_ongoing2.html.erb
<style>
 @import url(https://fonts.googleapis.com/css?family=Lato:400,700);


.login2_bar {
  width: 370px;
  height: 50px;
  background: #F7F7F7;
  border-radius: 10px;
  top: 50%;
  position: relative;
  z-index: 1;
  overflow: hidden;
}

.login2 {
  background: transparent;
  position: absolute;
  height: 100%;
  width: 260px;
  padding-left: 10px;
  text-align: left;
  font-size: 14px;
  border: none;
  line-height: 50px;
  vertical-align: middle;
  z-index: 10;
  -webkit-transition: transform 0.2s ease-in-out 0s;
     -moz-transition: transform 0.2s ease-in-out 0s;
       -o-transition: transform 0.2s ease-in-out 0s;
          transition: transform 0.2s ease-in-out 0s;
}

.login2_active {
  -webkit-transform: translateX(370px);
     -moz-transform: translateX(370px);
      -ms-transform: translateX(370px);
       -o-transform: translateX(370px);
          transform: translateX(370px);
}

.subscribe_button2:hover{
  background-color: #0091EA;
  /*#282828;*/
  cursor:pointer;
}

.subscribe_button2 {
  background: #1CA9FF;
  /*#383838;*/

  position: absolute;
  top: -50px;
  left: 271px;
  border-top-right-radius: 10px;
  border-bottom-right-radius: 10px;
  height: 140px;
  width: 100px;
  text-align: center;
  font-size: 14px;
  font-weight: 500;
  line-height: 150px;
  vertical-align: middle;
  color: white;
  -webkit-transition: transform 0.5s ease 0s;
     -moz-transition: transform 0.5s ease 0s;
       -o-transition: transform 0.5s ease 0s;
          transition: transform 0.5s ease 0s;
}

.subscribe_button2_active{
  -webkit-transform: translateY(50px);
     -moz-transform: translateY(50px);
      -ms-transform: translateY(50px);
       -o-transform: translateY(50px);
          transform: translateY(50px);
}

.subscribing2{
  background: #CDD4DC;
  height: 100%;
  width: 370px;
  z-index: 5;
  position: absolute;
  left:-370px;
  display: inline-block;
  -webkit-transition: transform 1s ease 0s ;
     -moz-transition: transform 1s ease 0s ;
       -o-transition: transform 1s ease 0s ;
          transition: transform 1s ease 0s ;
}

.subscribing2_active {
  -webkit-transform: translateX(370px);
     -moz-transform: translateX(370px);
      -ms-transform: translateX(370px);
       -o-transform: translateX(370px);
          transform: translateX(370px);
}

.thanks2{
  background: #FFCE00;
  height: 100%;
  width: 370px;
  z-index: 5;
  text-align: left;
  line-height: 50px;
  vertical-align: middle;
  padding-left: 10px;
  position: absolute;
  top:50px;
  display: inline-block;
  -webkit-transition: transform 0.5s ease 0s ;
     -moz-transition: transform 0.5s ease 0s ;
       -o-transition: transform 0.5s ease 0s ;
          transition: transform 0.5s ease 0s ;
}

.thanks2_active {
  -webkit-transform: translateY(-50px);
     -moz-transform: translateY(-50px);
      -ms-transform: translateY(-50px);
       -o-transform: translateY(-50px);
          transform: translateY(-50px);
}

</style>

<p class="sub">Be the first to know <span>&</span> get Kilometers</p>
<div class="login2_bar">
  <%= form_for @user, url: users_email_verification_path, method: :post do |f| %>
    <%= f.text_field :email, class: "login2", :placeholder => "Type in your email" %>
    <input class="submit subscribe_button2" onclick="subscribeOnClick()" name="commit" type="submit" value="Step Inside" />
  <% end %>
  <span class="subscribing2"></span>
  <span class="thanks2">Thank you. Verify your email to get early access.</span>
</div>

<script>
var subscribe_button2 = document.querySelector(".subscribe_button2");

subscribe_button2.addEventListener('click', function(){
  var subscribing2 = document.querySelector(".subscribing2");
  var thanks2 = document.querySelector(".thanks2");
  var login2 = document.querySelector(".login2");

  subscribing2.classList.add("subscribing2_active");
  subscribe_button2.classList.add("subscribe_button2_active");
  setTimeout(function(){
    login2.classList.add("login2_active");
  }, 1200);
  setTimeout(function(){
    thanks2.classList.add("thanks2_active");
  }, 1400);

  setTimeout(function(){
    thanks2.classList.remove("thanks2_active");
    login2.classList.remove("login2_active");
    subscribing2.classList.remove("subscribing2_active");
    subscribe_button2.classList.remove("subscribe_button2_active");
  }, 4000000);
});
</script>

app/views/shared/_campaign_ongoing3.html.erb
<style>
 @import url(https://fonts.googleapis.com/css?family=Lato:400,700);


.login3_bar {
  width: 370px;
  height: 50px;
  background: #F7F7F7;
  border-radius: 10px;
  top: 50%;
  position: relative;
  z-index: 1;
  overflow: hidden;
}

.login3 {
  background: transparent;
  position: absolute;
  height: 100%;
  width: 260px;
  padding-left: 10px;
  text-align: left;
  font-size: 14px;
  border: none;
  line-height: 50px;
  vertical-align: middle;
  z-index: 10;
  -webkit-transition: transform 0.2s ease-in-out 0s;
     -moz-transition: transform 0.2s ease-in-out 0s;
       -o-transition: transform 0.2s ease-in-out 0s;
          transition: transform 0.2s ease-in-out 0s;
}

.login3_active {
  -webkit-transform: translateX(370px);
     -moz-transform: translateX(370px);
      -ms-transform: translateX(370px);
       -o-transform: translateX(370px);
          transform: translateX(370px);
}

.subscribe_button3:hover{
  background-color: #0091EA;
  /*#282828;*/
  cursor:pointer;
}

.subscribe_button3 {
  background: #1CA9FF;
  /*#383838;*/

  position: absolute;
  top: -50px;
  left: 271px;
  border-top-right-radius: 10px;
  border-bottom-right-radius: 10px;
  height: 150px;
  width: 100px;
  text-align: center;
  font-size: 14px;
  line-height: 150px;
  vertical-align: middle;
  color: white;
  -webkit-transition: transform 0.5s ease 0s;
     -moz-transition: transform 0.5s ease 0s;
       -o-transition: transform 0.5s ease 0s;
          transition: transform 0.5s ease 0s;
}

.subscribe_button3_active{
  -webkit-transform: translateY(50px);
     -moz-transform: translateY(50px);
      -ms-transform: translateY(50px);
       -o-transform: translateY(50px);
          transform: translateY(50px);
}

.subscribing3{
  background: #CDD4DC;
  height: 100%;
  width: 370px;
  z-index: 5;
  position: absolute;
  left:-370px;
  display: inline-block;
  -webkit-transition: transform 1s ease 0s ;
     -moz-transition: transform 1s ease 0s ;
       -o-transition: transform 1s ease 0s ;
          transition: transform 1s ease 0s ;
}

.subscribing3_active {
  -webkit-transform: translateX(370px);
     -moz-transform: translateX(370px);
      -ms-transform: translateX(370px);
       -o-transform: translateX(370px);
          transform: translateX(370px);
}

.thanks3{
  background: #FFCE00;
  height: 100%;
  width: 370px;
  z-index: 5;
  text-align: left;
  line-height: 50px;
  vertical-align: middle;
  padding-left: 10px;
  position: absolute;
  top:50px;
  display: inline-block;
  -webkit-transition: transform 0.5s ease 0s ;
     -moz-transition: transform 0.5s ease 0s ;
       -o-transition: transform 0.5s ease 0s ;
          transition: transform 0.5s ease 0s ;
}

.thanks3_active {
  -webkit-transform: translateY(-50px);
     -moz-transform: translateY(-50px);
      -ms-transform: translateY(-50px);
       -o-transform: translateY(-50px);
          transform: translateY(-50px);
}

</style>

<p class="sub">Be the first to know <span>&</span> get Kilometers</p>
<div class="login3_bar">
  <%= form_for @user, url: users_email_verification_path, method: :post do |f| %>
    <%= f.text_field :email, class: "login3", :placeholder => "Type in your email" %>
    <input class="submit subscribe_button3" onclick="subscribeOnClick()" name="commit" type="submit" value="Step Inside" />
  <% end %>
  <span class="subscribing3"></span>
  <span class="thanks3">Thank you. Verify your email to get early access.</span>
</div>

<script>
var subscribe_button3 = document.querySelector(".subscribe_button3");

subscribe_button3.addEventListener('click', function(){
  var subscribing3 = document.querySelector(".subscribing3");
  var thanks3 = document.querySelector(".thanks3");
  var login3 = document.querySelector(".login3");

  subscribing3.classList.add("subscribing3_active");
  subscribe_button3.classList.add("subscribe_button3_active");
  setTimeout(function(){
    login3.classList.add("login3_active");
  }, 1200);
  setTimeout(function(){
    thanks3.classList.add("thanks3_active");
  }, 1400);

  setTimeout(function(){
    thanks3.classList.remove("thanks3_active");
    login3.classList.remove("login3_active");
    subscribing3.classList.remove("subscribing3_active");
    subscribe_button3.classList.remove("subscribe_button3_active");
  }, 4000000);
});
</script>

app/views/shared/_campaign_ongoing_footer.html.erb
<style>
 @import url(https://fonts.googleapis.com/css?family=Lato:400,700);

.login4_bar {
  display: flex;
  width: 280px;
  height: 40px;
  background: #F7F7F7;
  border-radius: 10px;
  top: 50%;
  position: relative;
  z-index: 0;
  overflow: hidden;
  margin: 0;
}

.login4 {
  background: transparent;
  position: absolute;
  height: 100%;
  width: 180px;
  padding-left: 10px;
  text-align: left;
  font-size: 12px;
  border: none;
  line-height: 40px;
  vertical-align: middle;
  z-index: 10;
  -webkit-transition: transform 0.2s ease-in-out 0s;
     -moz-transition: transform 0.2s ease-in-out 0s;
       -o-transition: transform 0.2s ease-in-out 0s;
          transition: transform 0.2s ease-in-out 0s;
}

.login4_active {
  -webkit-transform: translateX(280px);
     -moz-transform: translateX(280px);
      -ms-transform: translateX(280px);
       -o-transform: translateX(280px);
          transform: translateX(280px);
}

.subscribe_button4:hover{
  background-color: #00D99C;
  /*#282828;*/
  cursor:pointer;
}

.subscribe_button4 {
  background: #00FFB7;
  /*#383838;*/

  position: absolute;
  top: -40px;
  left: 190px;
  border-top-right-radius: 10px;
  border-bottom-right-radius: 10px;
  height: 120px;
  width: 91px;
  text-align: center;
  font-size: 12px;
  font-weight: 500;
  line-height: 100px;
  vertical-align: middle;
  color: black;
  -webkit-transition: transform 0.5s ease 0s;
     -moz-transition: transform 0.5s ease 0s;
       -o-transition: transform 0.5s ease 0s;
          transition: transform 0.5s ease 0s;
}

.subscribe_button4_active{
  -webkit-transform: translateY(40px);
     -moz-transform: translateY(40px);
      -ms-transform: translateY(40px);
       -o-transform: translateY(40px);
          transform: translateY(40px);
}

.subscribing4{
  background: #CDD4DC;
  height: 100%;
  width: 280px;
  z-index: 5;
  position: absolute;
  left:-280px;
  display: inline-block;
  -webkit-transition: transform 1s ease 0s ;
     -moz-transition: transform 1s ease 0s ;
       -o-transition: transform 1s ease 0s ;
          transition: transform 1s ease 0s ;
}

.subscribing4_active {
  -webkit-transform: translateX(280px);
     -moz-transform: translateX(280px);
      -ms-transform: translateX(280px);
       -o-transform: translateX(280px);
          transform: translateX(280px);
}

.thanks4{
  background: #00FFB7;
  height: 100%;
  width: 280px;
  z-index: 5;
  text-align: left;
  line-height: 40px;
  vertical-align: middle;
  padding-left: 10px;
  position: absolute;
  font-size: 12px;
  top:40px;
  display: inline-block;
  -webkit-transition: transform 0.5s ease 0s ;
     -moz-transition: transform 0.5s ease 0s ;
       -o-transition: transform 0.5s ease 0s ;
          transition: transform 0.5s ease 0s ;
}

.thanks4_active {
  -webkit-transform: translateY(-40px);
     -moz-transform: translateY(-40px);
      -ms-transform: translateY(-40px);
       -o-transform: translateY(-40px);
          transform: translateY(-40px);
}

</style>

<p class="sub">Be The First To Know <span>&</span> Get Kilometers</p>
<div class="login4_bar">
  <%= form_for @user, url: users_subscribe_path, method: :post do |f| %>
    <%= f.text_field :email, class: "login4", :placeholder => "Type in your email" %>
    <input class="submit subscribe_button4" onclick="subscribeOnClick()" name="commit" type="submit" value="Step Inside" />
  <% end %>
  <span class="subscribing4"></span>
  <span class="thanks4">Thank you. Verify your email to get early access.</span>
                                                                        <p></p>
</div>

<script>
var subscribe_button4 = document.querySelector(".subscribe_button4");

subscribe_button4.addEventListener('click', function(){
  var subscribing4 = document.querySelector(".subscribing4");
  var thanks4 = document.querySelector(".thanks4");
  var login4 = document.querySelector(".login4");

  subscribing4.classList.add("subscribing4_active");
  subscribe_button4.classList.add("subscribe_button4_active");
  setTimeout(function(){
    login4.classList.add("login4_active");
  }, 1200);
  setTimeout(function(){
    thanks4.classList.add("thanks4_active");
  }, 1400);

  setTimeout(function(){
    thanks4.classList.remove("thanks4_active");
    login4.classList.remove("login4_active");
    subscribing4.classList.remove("subscribing4_active");
    subscribe_button4.classList.remove("subscribe_button4_active");
  }, 4000000);
});
</script>

app/views/shared/_contact-form.html.erb
<%= form_for @contact, url: contact_index_path, method: :post, id: "contact-form", remote: true do |f| %>
  </br>
  </br>
  <%= f.text_field  :name, :placeholder => "Name", id: "contact-user-info", required: true, class: "contact-form-text-area" %></br>

  </br>
  </br>
  <%= f.text_field :email, :placeholder => "Email", id: "contact-user-info", required: true, class: "contact-form-text-area" %></br>

  </br>
  </br>
  <%= f.text_field :phone, :placeholder => "Phone Number", id: "contact-user-info", required: true, class: "contact-form-text-area" %></br>

  </br>
  </br>
  <%= f.text_area :message, id: "contact-user-info", rows:9, cols: 72, required: true, class: "contact-form-text-area", placeholder: "Message"%></br>
  </br>
  <%= f.submit 'Send', class: 'btn-submit' %>
<% end %>

app/views/shared/_footer-mobile.html.erb
<div class="footer-mobile-container">
  <div class="footer-top-container">
    <%= link_to root_path do %>
      <%= image_tag('Logo/Logo-white@2x.png', class: 'logo-image') %>
    <% end %>
    <div class="list-menu">
      <ul class="list">
        <li>Yoda Bike</li>
        <li><%= link_to rent_a_yoda_path do %>Rent a Yoda<% end %></li>
        <li><%= link_to "#order" do %>Buy a Yoda<% end %></li>
        <li><a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/yodacity-test-ride/30min'});return false;">Test a Yoda</a></li>
        <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
        <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript"></script>
      </ul>
      <ul class="list">
        <li>Company</li>
        <li><%= link_to contact_path do %>Contact Us<% end %></li>
        <li><%= link_to faq_path do %>FAQ<% end %></li>
        <li><%= link_to root_path do %>News<% end %></li>
      </ul>
    </div>
    <div class="newsletter-container">
      <div class="newsletter-content-mobile">
        <p>Subscribe To Our Newsletter</p>
        <%= form_for @user, url: users_subscribe_path, method: :post, class: "footer-form" do |f| %>
          <%= f.text_field :email, :placeholder => "Type in your email" %>
          <submit type="submit"><i class="fas fa-arrow-right"></i></submit>
        <% end %>
      </div>
    </div>
    <div class="social-links">
      <div class="social">
        <%= link_to "https://www.facebook.com/yodacity/?modal=admin_todo_tour" do%><i class="fab fa-facebook-square"></i><% end %>
        <%= link_to "https://www.instagram.com/yodacity" do%><i class="fab fa-instagram"></i><% end %>
        <%= link_to "https://www.linkedin.com/company/yodacity" do%><i class="fab fa-linkedin"></i><% end %>
      </div>
    </div>
    <div class="infos-contact">
      <p>Chaussée de Waterloo 834, 1180<br>Brussels, Belgium</p>
      <p>+32/472.22.22.05</p>
      <p>contact@yoda-city.com</p>
    </div>
  </div>
  <div class="footer-bottom-container">
    <div class="legal-menu-footer">
      <%= link_to terms_of_use_path do %>Terms of use<% end %>
      <%= link_to privacy_policy_path do %>Privacy policy<% end %>
      <p>© 2020 YodaCity</p>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer-container">

  <div class="footer-container-top">
    <div class="footer-content-top">
      <div class="brand">
        <div class="footer-logo">
          <%= link_to root_path do %>
            <%= image_tag('Logo/Logo-white@2x.png', class: 'logo-image') %>
          <% end %>
        </div>
        <div class="social-network">
          <p>Follow Us</p>
          <div class="icon">
            <%= link_to "https://www.facebook.com/yodacity/?modal=admin_todo_tour" do%><i class="fab fa-facebook-square"></i><% end %>
            <%= link_to "https://www.instagram.com/yodacity" do%><i class="fab fa-instagram"></i><% end %>
            <%= link_to "https://www.linkedin.com/company/yodacity" do%><i class="fab fa-linkedin"></i><% end %>
          </div>
        </div>
      </div>
      <ul class="list">
        <li>Yoda Bike</li>
        <li><%= link_to rent_a_yoda_path do %>Rent a Yoda<% end %></li>
        <li><%= link_to "#order" do %>Buy a Yoda<% end %></li>
        <li><a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/yodacity-test-ride/30min'});return false;">Test a Yoda</a></li>
        <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
        <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript"></script>
      </ul>
      <ul class="list">
        <li>Company</li>
        <li><%= link_to contact_path do %>Contact Us<% end %></li>
        <li><%= link_to faq_path do %>FAQ<% end %></li>
        <li><%= link_to root_path do %>News<% end %></li>
      </ul>
      <div class="newsletter">
        <div class="newsletter-content">
          <%= render "shared/campaign_ongoing_footer" %>
        </div>
        <div class="infos-contact">
          <p>Chaussée de Waterloo 834<br>1180, Brussels, Belgium</p>
          <p>+32/472.22.22.05</p>
          <p>contact@yoda-city.com</p>
        </div>
      </div>
    </div>
  </div>

  <div class="footer-container-bottom">
    <div class="footer-content-bottom">
      <div class="legal-menu-footer">
        <%= link_to terms_of_use_path do %>Terms of use<% end %>
        <%= link_to privacy_policy_path do %>Privacy policy<% end %>
        <p>© 2020 YodaCity</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar-mobile.html.erb
<nav class="nav-mobile-container">
  <div class="nav-mobile-content">
    <div class="nav-mobile-logo-black">
      <%= link_to root_path do %>
        <%= image_tag('Logo/Logo@2x.png', class: "logo-nav") %>
      <% end %>
    </div>
    <div class="nav-mobile-logo-white">
      <%= link_to root_path do %>
        <%= image_tag('Logo/Logo-white@2x.png', class: "logo-nav") %>
      <% end %>
    </div>
  </div>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</nav>

<div class="nav-footer-container">
  <div class="btn-mobile-content">
    <% if @rent_navbar %>
      <%= link_to "#km-order" do %>
        <div class="nav-mobile-btn rent">
          <p>Get free km</p>
        </div>
      <% end %>
      <%= link_to root_path do %>
        <div class="nav-mobile-btn buy">
          <p>Buy a Yoda</p>
        </div>
      <% end %>
    <% elsif @refer_friend_navbar %>
      <%= link_to "#km-order" do %>
        <div class="nav-mobile-btn rent">
          <p>50% on km</p>
        </div>
      <% end %>
    <%= link_to root_path do %>
        <div class="nav-mobile-btn buy">
          <p>Order now</p>
        </div>
      <% end %>
    <% else %>
      <%= link_to rent_a_yoda_path do %>
        <div class="nav-mobile-btn rent">
          <p>Rent a Yoda</p>
        </div>
      <% end %>
      <%= link_to "#order" do %>
        <div class="nav-mobile-btn buy">
          <p>Order now</p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="nav-container">
  <div class="nav-content">
    <div class="nav-logo-black">
      <%= link_to root_path do %>
        <%= image_tag('Logo/Logo@2x.png', class: "logo-black") %>
      <% end %>
    </div>
    <div class="nav-logo-white">
      <%= link_to root_path do %>
        <%= image_tag('Logo/Logo-white@2x.png', class: "logo-white") %>
      <% end %>
    </div>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <div class="btn-container">
      <% if @rent_navbar %>
        <%= link_to "#km-order" do%><div class="nav-btn rent">Get free km</div><% end %>
        <%= link_to root_path do%><div class="nav-btn buy">Buy a Yoda</div><% end %>
      <% elsif @refer_friend_navbar %>
        <%= link_to "#km-order" do%><div class="nav-btn rent">50% on km</div><% end %>
        <%= link_to roots_path do%><div class="nav-btn buy">Buy a Yoda</div><% end %>
      <% else %>
        <%= link_to rent_a_yoda_path do%><div class="nav-btn rent">Rent a Yoda</div><% end %>
        <%= link_to "#order" do%><div class="nav-btn buy">Order now</div><% end %>
      <% end %>
    </div>
  </div>
</nav>