config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'pages#main'

  get 'rent-a-yoda' => 'pages#rent'
  get 'cart' => 'pages#cart'
  get 'warranty' => 'pages#warranty'
  get 'faq' => 'pages#faq'
  get 'delivery' => 'pages#delivery'
  get 'returns' => 'pages#returns'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'terms-of-use' => 'pages#terms_of_use'


  resources :contact, only: [:create]
  get 'contact' => 'contact#contact'


  get 'users/create' => 'users#create'
  post 'users/subscribe' => 'users#create_subscriber'
  post 'users/email-verification' => 'users#email_verification'
  get 'rent-a-yoda/refer-a-friend' => 'users#refer'
end

app/views/pages/faq.html+phone.erb
<%= render "shared/navbar-mobile" %>
<div class="infos-page-mobile-container">
  <div class="infos-page-mobile-content">
    <h1>Frequently<br>Asked<br>Questions</h1>
    <h2>The Yoda riding experience</h2>
    <div class="faq-question">
      <h5>Is this an e-bike, a moped, or what?</h5>
      <p>The Yoda bike was designed to provide the riding experience of a bike (everyone knows how to ride a bicycle), with the advantages of a motorcycle (you can go up to 45 km/h without sweating).</p>
    </div>
    <div class="faq-question">
      <h5>Do I need a license/license plate/insurance to drive a Yoda?</h5>
      <p>When renting a Yoda from us (Belgium,), you need either a type B license (regular car license), or an A3 or AM motorcycle license. You are insured for rides made through our application.</p>
      <p>To use your own Yoda, you may need a license, license plate, and insurance depending on the laws of the country in which you ride. For instance in Belgium, you will need:</p>
      <ul>
        <li>Either a type B license (regular car license), or an A3 or AM motorcycle license (which can be obtained if you are 16 or above).</li>
        <li>To apply for a license plate for class B mopeds. These begin with the letters “SB”.</li>
        <li>A liability insurance policy (”Burgerlijke Aansprakelijkheid”/“Responsabilité Civile”).</li>
      </ul>
      <p>We will provide you with detailed step-by-step guidance when delivering your Yoda to you.</p>
    </div>
    <div class="faq-question">
      <h5>Do I need a helmet?</h5>
      <p>Yes, most countries have laws requiring to wear helmets. For instance, in Belgium, you’ll need to wear a moped/motorcycle E-marked helmet.</p>
    </div>
    <div class="faq-question">
      <h5>Can I drive a Yoda on bike lanes?</h5>
      <p>It depends on the laws of the country in which you ride. For instance in Belgium, YES you can in most cases use bike lanes marked by this sign</p>
      <div class="img-bike-lanes-container">
        <%= image_tag('Bike-lanes-sign.png', class: "bike-lanes") %>
      </div>
      <p>More information is available<a href="https://www.permisdeconduire-online.be/theorie/theorie-permis-am/ou-devez-vous-rouler-avec-votre-motoclyclette"> here (français)</a> and <a href="https://www.gratisrijbewijsonline.be/theorie/leerstof-rijbewijs-am/fietser-fietspad-oversteekplaats"> here (Nederlands)</a>.</p>
    </div>
    <div class="faq-question">
      <h5>Can I use a bike rack on a Yoda?</h5>
      <p>No. Our betas testers typically carry things around with a backpack. Unlike when riding a bike, you won’t sweat so it’s not uncomfortable.</p>
    </div>
    <div class="faq-question">
      <h5>What if I don’t have a smartphone, or my phone runs out of battery?</h5>
      <p>At your request, we can provide you with a smartcard to allow you to unlock your Yoda without your phone, or rent out Yodas in free-floating.</p>
    </div>

    <h2>Pre-order</h2>
    <div class="faq-question">
      <h5>When will my Yoda be delivered to me?</h5>
      <p>We’re doing everything in our power for this date to be as soon as possible. We are targeting June 2020. Bear in mind however that some things are out of our hands. These include our suppliers timelines and the timeline of the administration providing the homologation. We will keep you informed of any significant delay.
      </p>
    </div>
    <div class="faq-question">
      <h5>What is included in the price?</h5>
      <p>The price of a fully-functional street-legal Yoda is 2490 EUR and includes VAT. A charger costs 100 EUR VAT included. The price does not include delivery. You will have the option to pick up your Yoda at our main office in Uccle (Brussels, Belgium) free of charge, or have the Yoda delivered to you at an address in Belgium, for a fee (estimated as 50 EUR).</p>
    </div>
    <div class="faq-question">
      <h5>Will I have to assemble my Yoda?</h5>
      <p>If you choose to receive your Yoda, you will get a box containing the Yoda, instructions, and tools to finalize assembly. Assembly will take 5 minutes and require no skills.</p>
    </div>
    <div class="faq-question">
      <h5>Why should I reserve a Yoda today?</h5>
      <p>Your deposit guarantees that you’ll be able to buy one of the Yodas we manufacture in the next batch, which will be limited in size. The next batch of Yodas will be 2990 EUR, and scheduled for end of 2020.</p>
    </div>
    <div class="faq-question">
      <h5>What if I change my mind and do not want a Yoda anymore?</h5>
      <p>Your deposit is 100% refundable, no questions asked. Once your Yoda is delivered to you, you have up to 14 days to change your mind, and return your Yoda to receive a full refund.</p>
    </div>
    <div class="faq-question">
      <h5>Can I reserve one if I don’t live in Belgium?</h5>
      <p><%= link_to contact_path do %>Please contact us.<% end %></p>
    </div>
    <div class="faq-question">
      <h5>Is there a warranty?</h5>
      <p><%= link_to warranty_path do %>Check out the warranty terms.<% end %> </p>
    </div>
  </div>
</div>
<%= render "shared/footer-mobile" %>
<div class="footer-mobile-height"></div>


<script>
  $(document).ready(function() {
      $(window).scroll(function() {
          var height = $('.page-1-mobile-content').height();
          var scrollTop = $(window).scrollTop();
          $('.nav-mobile-logo-white').css('display', 'none');
          $('.nav-mobile-logo-black').css('display', 'inline');
          $('.solid-mobile-nav').css('background-color', 'transparent');

          if (scrollTop >= height - height*0.96) {
              $('.solid-mobile-nav').css('background-color', 'white');
              $('.nav-mobile-container').addClass('solid-mobile-nav');
          } else {
              $('.nav-mobile-container').removeClass('solid-mobile-nav');
          }
      });
  });
</script>
<%= render "shared/fb-messenger" %>

app/views/pages/faq.html.erb
<%= render "shared/navbar" %>
<div class="navbar-height"></div>

<div class="infos-page-container">
  <div class="infos-page-content">
    <h1>Frequently Asked Questions</h1>
    <h2>The Yoda riding experience</h2>
    <div class="faq-question">
      <h5>Is this an e-bike, a moped, or what?</h5>
      <p>The Yoda bike was designed to provide the riding experience of a bike (everyone knows how to ride a bicycle), with the advantages of a motorcycle (you can go up to 45 km/h without sweating).</p>
    </div>
    <div class="faq-question">
      <h5>Do I need a license/license plate/insurance to drive a Yoda?</h5>
      <p>When renting a Yoda from us (Belgium,), you need either a type B license (regular car license), or an A3 or AM motorcycle license. You are insured for rides made through our application.</p>
      <p>To use your own Yoda, you may need a license, license plate, and insurance depending on the laws of the country in which you ride. For instance in Belgium, you will need:</p>
      <ul>
        <li>Either a type B license (regular car license), or an A3 or AM motorcycle license (which can be obtained if you are 16 or above).</li>
        <li>To apply for a license plate for class B mopeds. These begin with the letters “SB”.</li>
        <li>A liability insurance policy (”Burgerlijke Aansprakelijkheid”/“Responsabilité Civile”).</li>
      </ul>
      <p>We will provide you with detailed step-by-step guidance when delivering your Yoda to you.</p>
    </div>
    <div class="faq-question">
      <h5>Do I need a helmet?</h5>
      <p>Yes, most countries have laws requiring to wear helmets. For instance, in Belgium, you’ll need to wear a moped/motorcycle E-marked helmet.</p>
    </div>
    <div class="faq-question">
      <h5>Can I drive a Yoda on bike lanes?</h5>
      <p>It depends on the laws of the country in which you ride. For instance in Belgium, YES you can in most cases use bike lanes marked by this sign</p>
      <div class="img-bike-lanes-container">
        <%= image_tag('Bike-lanes-sign.png', class: "bike-lanes") %>
      </div>
      <p>More information is available<a href="https://www.permisdeconduire-online.be/theorie/theorie-permis-am/ou-devez-vous-rouler-avec-votre-motoclyclette"> here (français)</a> and <a href="https://www.gratisrijbewijsonline.be/theorie/leerstof-rijbewijs-am/fietser-fietspad-oversteekplaats"> here (Nederlands)</a>.</p>
    </div>
    <div class="faq-question">
      <h5>Can I use a bike rack on a Yoda?</h5>
      <p>No. Our betas testers typically carry things around with a backpack. Unlike when riding a bike, you won’t sweat so it’s not uncomfortable.</p>
    </div>
    <div class="faq-question">
      <h5>What if I don’t have a smartphone, or my phone runs out of battery?</h5>
      <p>At your request, we can provide you with a smartcard to allow you to unlock your Yoda without your phone, or rent out Yodas in free-floating.</p>
    </div>

    <h2>Pre-order</h2>
    <div class="faq-question">
      <h5>When will my Yoda be delivered to me?</h5>
      <p>We’re doing everything in our power for this date to be as soon as possible. We are targeting June 2020. Bear in mind however that some things are out of our hands. These include our suppliers timelines and the timeline of the administration providing the homologation. We will keep you informed of any significant delay.
      </p>
    </div>
    <div class="faq-question">
      <h5>What is included in the price?</h5>
      <p>The price of a fully-functional street-legal Yoda is 2490 EUR and includes VAT. A charger costs 100 EUR VAT included. The price does not include delivery. You will have the option to pick up your Yoda at our main office in Uccle (Brussels, Belgium) free of charge, or have the Yoda delivered to you at an address in Belgium, for a fee (estimated as 50 EUR).</p>
    </div>
    <div class="faq-question">
      <h5>Will I have to assemble my Yoda?</h5>
      <p>If you choose to receive your Yoda, you will get a box containing the Yoda, instructions, and tools to finalize assembly. Assembly will take 5 minutes and require no skills.</p>
    </div>
    <div class="faq-question">
      <h5>Why should I reserve a Yoda today?</h5>
      <p>Your deposit guarantees that you’ll be able to buy one of the Yodas we manufacture in the next batch, which will be limited in size. The next batch of Yodas will be 2990 EUR, and scheduled for end of 2020.</p>
    </div>
    <div class="faq-question">
      <h5>What if I change my mind and do not want a Yoda anymore?</h5>
      <p>Your deposit is 100% refundable, no questions asked. Once your Yoda is delivered to you, you have up to 14 days to change your mind, and return your Yoda to receive a full refund.</p>
    </div>
    <div class="faq-question">
      <h5>Can I reserve one if I don’t live in Belgium?</h5>
      <p><%= link_to contact_path do %>Please contact us.<% end %> </p>
    </div>
    <div class="faq-question">
      <h5>Is there a warranty?</h5>
      <p><%= link_to warranty_path do %>Check out the warranty terms.<% end %> </p>
    </div>
  </div>
</div>

<%= render "shared/footer" %>
<script>
  $('.nav-logo-white').css('display', 'none');
  $('.nav-logo-black').css('display', 'inline');

  $('.rent').css('border-color', 'black');
  $('.rent').css('background-color', 'white');
  $('.rent').css('color', 'black');
  $('.buy').css('border-color', 'black');
  $('.buy').css('background-color', 'black');
  $('.buy').css('color', 'white');
  $(document).ready(function() {
      $(window).scroll(function() {
          var height = $('.page-1-content').height();
          var scrollTop = $(window).scrollTop();
          if (scrollTop >= height - height*0.96) {
            $('.nav-logo-white').css('display', 'none');
            $('.nav-logo-black').css('display', 'inline');

            $('.rent').css('border-color', 'black');
            $('.rent').css('background-color', 'white');
            $('.rent').css('color', 'black');
            $('.buy').css('border-color', 'black');
            $('.buy').css('background-color', 'black');
            $('.buy').css('color', 'white');
              $('.nav-container').addClass('solid-nav');
          } else {
              $('.nav-container').removeClass('solid-nav');
          }
      });
  });
</script>

app/views/pages/main.html+phone.erb
<%= render "shared/navbar-mobile" %>

<div class="main-mobile-container">
  <div class="page-mobile-container">
    <div class="page-mobile-content-1">
      <div class="text-container">
        <div class="text-content">
          <h1>Simply fun<span>.</span></h1>
          <p>At 27 kg, forget about heavy and complicated.<br>Zip through traffic like never before on a Yoda.</p>
          <%= link_to "#order" do %>Reserve yours for 500€<% end %>
        </div>
      </div>
      <div class="image">
        <%= image_tag('Yoda/Mobile/Black-Yoda-main-app@2x.png') %>
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <div class="page-mobile-content-2">
      <h2>Manage your juice<span>.</span></h2>
      <div class="image">
        <%= image_tag('App/Mobile/Iphone_X-eco-app-mobile-buy-2@2x.png') %>
      </div>
      <div class="ecomode-container">
        <div class="eco">
          <%= image_tag('App/Eco-mode-On@2x.png') %>
          <p>Economic mode <span>[30 km/h - 65 km]</span></p>
        </div>
        <div class="eco">
          <%= image_tag('App/Eco-mode-Off@2x.png') %>
          <p>Regular mode <span>[45 km/h - 50 km]</span></p>
        </div>
        <!-- Calendly link widget begin -->
        <link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet">
        <script src="https://assets.calendly.com/assets/external/widget.js" type="text/javascript"></script>
        <a href="" onclick="Calendly.initPopupWidget({url: 'https://calendly.com/yodacity-test-ride/30min'});return false;">Book a test ride</a>
        <!-- Calendly link widget end -->
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <div class="page-mobile-content-3">
      <div class="text-container">
        <div class="text-content">
          <h2>Feels good<span>.</span></h2>
          <p>Riding posture and components optimized for comfort.</p>
          <%= link_to "#order" do %>Reserve yours for 500€<% end %>
        </div>
      </div>
      <div class="image">
        <%= image_tag('Yoda/Mobile/Yoda-back-view-pain-mobile-buy-3@2x.png') %>
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <div class="page-mobile-content-4">
      <div class="text-container">
        <div class="text-content">
          <h2>Safe like <br>a bicycle<span>.</span></h2>
          <p>You can use the bike lanes, courtesy<br>of the law.</p>
        </div>
      </div>
      <div class="image">
        <%= image_tag('Yoda/Mobile/Front-back-view-mobile@2x.png') %>
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <div class="page-mobile-content-5">
      <div class="text-container">
        <div class="text-content">
          <h2>Charge anywhere<span>.</span></h2>
          <p>Take the battery with you. Full charge in 4 hours.</p>
          <%= link_to "#order" do %>Reserve yours for 500€<% end %>
        </div>
      </div>
      <div class="image">
        <%= image_tag('Yoda/Mobile/Yoda-battery-mobile-buy-4@2x.png') %>
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <div class="page-mobile-content-6">
      <div class="text-container">
        <div class="text-content">
          <h2>Go the distance<span>.</span></h2>
          <p>Ride uphill, downhill, on-road, off-road. Nothing stops a Yoda.</p>
          <%= link_to "#order" do %>Reserve yours for 500€<% end %>
        </div>
      </div>
      <div class="image">
        <%= image_tag('Yoda/Mobile/Yoda-buy-mobile-go-distance@2x.png') %>
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <section id="slideshow-wrapper">
      <div id="Slideshow">
        <div id="Slider">
          <div id="slide" class="first-second">
            <div class="text-container">
              <h3>Peace of mind<span>.</span></h3>
              <p>Be notified of suspicious activity.</p>
            </div>
            <div class="image">
              <%= image_tag('App/Mobile/Iphone_X-notif-home-theft-mobile@2x.png') %>
            </div>
          </div>
          <div id="slide" class="first-second">
            <div class="text-container">
              <h3>Track your Yoda<span>.</span></h3>
              <p>Geo-localize your stolen bike.</p>
            </div>
            <div class="image">
              <%= image_tag('App/Mobile/Iphone_X-track-map-theft-mobile@2x.png') %>
            </div>
          </div>
          <div id="slide" class="third">
            <div class="text-container">
              <h3>Motor locked<span>.</span></h3>
              <p>Opportunity thieves wont hijack your Yoda.</p>
            </div>
          </div>
        </div>
        <div id="Arrows">
          <i id="Prev" class="fa fa-chevron-left fa-2x" aria-hidden="true"></i>
          <i id="Next" class="fa fa-chevron-right fa-2x" aria-hidden="true"></i>
        </div>
      </div>
    </section>
  </div>

  <div class="page-mobile-container">
    <div class="page-mobile-content-7">
      <div class="featurs-container">
        <div class="row">
          <div class="feature">
            <%= image_tag('Checkout/Battery-range@2x.png') %>
            <p class= "title">65 km</p><p>Range per charge</p>
          </div>
          <div class="feature">
            <%= image_tag('Checkout/Max-speed@2x.png') %>
            <p class= "title">45 km/h</p><p>Maximum Speed</p>
          </div>
          <div class="feature">
            <%= image_tag('Checkout/Weight@2x.png') %>
            <p class= "title">27 kg</p><p>The lightest motorcycle</p>
          </div>
        </div>
        <div id="order"></div>
        <div class="row">
          <div class="feature">
            <%= image_tag('Checkout/Charging-time@2x.png') %>
            <p class= "title">4 hours</p><p>Charging time</p>
          </div>
          <div class="feature">
            <%= image_tag('Checkout/Connectivity@2x.png') %>
            <p class= "title">Connectivity</p><p>Bluetooth Low Energy</p>
          </div>
          <div class="feature">
            <%= image_tag('Checkout/Street-legal@2x.png') %>
            <p class= "title">Street legal</p><p>Car license B or A3 or AM</p>
          </div>
        </div>
      </div>
      <div class="text-book">
        <h2>Book it now<span>.</span></h2>
        <p>Reserve your Yoda with a deposit of 500€.<br>Pay the balance at delivery.</p>
        <%= link_to "https://yodacity.myshopify.com/cart/31542945218659:1?channel=buy_button" do %>Reserve for 500€<% end %>
        <h4>2.490€</h4>
      </div>
      <div class="text-price">
        <!-- <p>Production of the Yoda First Edition begins February 2020.</p> -->
        <p>Production begins February 2020.</p>
        <p>Delivery starts mid-August 2020.</p>
        <p>Yodas on next production batch will cost 2.990€, for delivery late 2020.</p>
        <!-- <p>The Second Edition will cost 2.990€, for delivery late 2020.</p> -->
      </div>
    </div>
  </div>

  <div class="page-mobile-container">
    <div class="page-mobile-content-8">
      <div class="text-container">
        <div class="text-content">
          <h2>Book a test ride<span>.</span></h2>
          <p>Come try what it feels to ride a Yoda,<br>it’s completely free 😀</p>
        </div>
      </div>
      <!-- Calendly inline widget begin -->
      <div class="calendly-inline-widget" data-url="https://calendly.com/yodacity-test-ride/30min" style="min-width:320px;height:750px;"></div>
      <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js"></script>
      <!-- Calendly inline widget end -->
    </div>
  </div>
  <%= render "shared/footer-mobile" %>
  <div class="footer-mobile-height"></div>
</div>

<script>
  $(document).ready(function() {
      $(window).scroll(function() {
          var height = $('.page-mobile-content-1').height();
          var scrollTop = $(window).scrollTop();
          $('.nav-mobile-logo-white').css('display', 'none');
          $('.nav-mobile-logo-black').css('display', 'inline');
          $('.solid-mobile-nav').css('background-color', 'transparent');

          if (scrollTop >= height - height*0.96) {
              $('.solid-mobile-nav').css('background-color', 'white');
              $('.nav-mobile-container').addClass('solid-mobile-nav');
          } else {
              $('.nav-mobile-container').removeClass('solid-mobile-nav');
          }
      });
  });
</script>

<script>//Manual Slideshow with navigation arrow
  $("#Next").click(function(){
    $("#Slider").append($("#Slider #slide:first-of-type"));
  });

  $("#Prev").click(function(){
    $("#Slider").prepend($("#Slider #slide:last-of-type"));
  });
</script>

app/views/pages/privacy_policy.html+phone.erb
<%= render "shared/navbar-mobile" %>
<div class="infos-page-mobile-container">
  <div class="infos-page-mobile-content">
    <h1>Privacy policy</h1>
    <br>
    <p>YodaCity may use your personal data to provide you with its products and services. We do so in a manner that is respectful of your right to have your personal data protected, your rights to transparency of what we collect and do with it, and your rights to data ownership.We follow the rules set forth by European and Belgian laws and regulations such as GDPR.</p>
    <br>
    <p><b>The entity that collects your data (the “controller”)</b></p>
    <p>YodaCity SRL<br>Chaussée de Waterloo 834<br>1180 Uccle<br>Belgium<br>E-mail <a href="mailto:contact@yoda-city.com">contact@yoda-city.com</a><br>Company number 0737.514.160</p>
    <br>
    <p><b>Your behavior when you use our website, product and services</b></p>
    <p>We ask that you only provide personal data that you are entitled to communicate to us, particularly when communicating data on behalf of others. Please do not provide personal data when you contact us through social media.</p>
    <br>
    <p><b>The personal data that we collect, and why</b></p>
    <p><i>When you browse the website</i><br>We actually do not collect personal data, such as cookies, when you browse our website.</p>
    <p><i>When you subscribe to our newsletter</i><br>We collect your email address. This allows us to keep you informed of our sales, promotions, events and updates to our products and services.</p>
    <p><i>When you contact us by email, or through a form on the website</i><br>We collect your name and email address. This allows us to contact you back.</p>
    <p><i>When you register for a test ride</i><br>We collect your name, email address, telephone number and IP address. This allows us to send you a confirmation of the time and place of the test ride, greet you personally, and notify you of any cancellation that may arise due, for instance, to bad weather. Collecting the IP address is done to avoid misuse of the system and combat abuse.</p>
    <p><i>When you make a purchase</i><br>We collect your name, email address, telephone number, mailing address, and IP address. This allows us to fulfill our contract with you, including being able to contact you when your order is available. If you pay by bank transfer, we will also store your account information to be able to verify your identity, should you request a refund according to our terms and conditions. Collecting the IP address is done to avoid misuse of the system and combat abuse.</p>
    <br>
    <p><b>Data storage policy</b></p>
    <p>We rely on data processors to store personal data. These data processors may store the data in EU countries, or outside the EU (the US mainly). We have data processing agreements with all the data processors we rely on, which requires them to follow EU regulations. In particular, your data is encrypted and only accessible to the controller’s employee that require it to perform their job and duties. Additionally, we will not store data beyond a maximum of 36 months after the intent for which the data was collected does not exist (for instance, we’ll remove your info from our database after a maximum of 36 months after your test ride).</p>
    <br>
    <p><b>Collection of your personal data by third parties</b></p>
    <p>Proper functionality of certain website functions such as social media buttons, may rely on the use of cookies by data processors.</p>
    <br>
    <p><b>Collection of data for statistical purposes</b></p>
    <p>To improve the performance of the website and improve our products and services, we rely on data provided by data processors. These services may use cookies. The data provided to us for these purposes has been anonymized by the data processors.</p>
    <br>
    <p><b>Your rights regarding your personal data</b></p>
    <p>You have the right to access your personal data or obtain a copy of your data.<br>You have the right to update your data, such as e-mail, telephone number or address.<br>You have the right to delete your data. We can request deletion from third party service providers as well. Deletion of your data will be performed as soon as possible, within a maximum of 180 days, unless EU or EU member state law requires storage.<br>Contact us via this form, or e-mail <a href="mailto:contact@yoda-city.com">contact@yoda-city.com</a> to do so.</p>
    <p>You also have the right to file a complaint with the Data Protection Authority (in Belgium it is the “Autorité de protection des données / Gegevensbeschermingsautoriteit, Rue de la presse 35, 1000 Brussels, <a href="https://www.dataprotectionauthority.be">https://www.dataprotectionauthority.be</a>“).</p>
    <br>
    <p><b>Changes to this policy</b></p>
    <p>Changes to this policy may occur at any time to reflect changes in our products or services. We recommend you consult and read this policy regularly. If you do not agree with this policy anymore, we kindly request that you ask for deletion of your data to us.</p>
  </div>
</div>
<%= render "shared/footer-mobile" %>
<div class="footer-mobile-height"></div>


<script>
  $(document).ready(function() {
      $(window).scroll(function() {
          var height = $('.page-1-mobile-content').height();
          var scrollTop = $(window).scrollTop();
          $('.nav-mobile-logo-white').css('display', 'none');
          $('.nav-mobile-logo-black').css('display', 'inline');
          $('.solid-mobile-nav').css('background-color', 'transparent');

          if (scrollTop >= height - height*0.96) {
              $('.solid-mobile-nav').css('background-color', 'white');
              $('.nav-mobile-container').addClass('solid-mobile-nav');
          } else {
              $('.nav-mobile-container').removeClass('solid-mobile-nav');
          }
      });
  });
</script>
<%= render "shared/fb-messenger" %>

app/views/pages/yoyo.erb
<%= render "shared/navbar-mobile" %>

<div class="test-mobile-page-container">
  <div class="test-mobile-page-content">
    <div class="text-content">
      <h1>Wanna know <span>how it feel</span> ?</h1>
      <p>Book a test ride for free.</p>
    </div>
  </div>
</div>

<div class="calendly-inline-widget" data-url="https://calendly.com/yodacity-test-ride/30min"
style="min-width:320px;height:930px;"></div>
<%= render "shared/footer-mobile" %>



<script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js"></script>

<script>
  $(document).ready(function() {
      $(window).scroll(function() {
          var height = $('.page-1-mobile-content').height();
          var scrollTop = $(window).scrollTop();

          if (scrollTop >= height - height*0.96) {
            $('.nav-mobile-container').addClass('solid-mobile-nav');
            $('.nav-mobile-container').removeClass('solid-mobile-black-nav');
          } else {
            $('.nav-mobile-container').removeClass('solid-mobile-nav');
            $('.nav-mobile-container').removeClass('solid-mobile-black-nav');
          }
      });
  });
</script>